### ISSUE TITLE
Creer les tables pour les données et évenement HVAC dans la base de données

### ISSUE THREAD

**Issue by willBEts** [SimonCastonguayETS/oxygencs-grp1-eq12#5]
**Décrivez le problème que vous voulez résoudre**
les tables pour contenir les données et les évenements du HVAC n'existent pas.

**Décrivez la solution proposée**
Créer deux tables dans la base de données. 
une table "température du HVAC" avec comme colonnes :  "timestamp" et "température".
une table "évenement du HVAC" avec comme colonnes : "timestamp" et "évenement".

**Détails additionnels**

**Comment by domBougie** [comment]
![Image](https://github.com/SimonCastonguayETS/oxygencs-grp1-eq12/assets/98377054/14de418a-f398-4744-8581-0d017bfe1a12)
